name: acl_ssl
channels:
  - conda-forge
  - nvidia
  - pytorch
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=2.138=mkl
  - blas-devel=3.9.0=38_hcf00494_mkl
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-version=11.7=h67201e3_3
  - cudatoolkit=11.7.0=hd8887f6_10
  - cudnn=9.2.1.18=h93471f6_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_2
  - grpcio=1.74.1=py310h8f3b6d6_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hf-xet=1.2.0=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jasper=4.2.8=he3c4edf_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_ha6a0dec_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=38_h5875eb1_mkl
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=38_hfef963f_mkl
  - libclang-cpp21.1=21.1.5=default_h99862b1_0
  - libclang13=21.1.5=default_h746c552_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_1
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.74.1=h3288cfb_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - liblapack=3.9.0=38_h5e43f62_mkl
  - liblapacke=3.9.0=38_hdba1596_mkl
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopencv=4.12.0=qt6_py310hdb0ca46_607
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.8.0=cpu_mkl_h09b866c_102
  - libudev1=257.9=h085a93f_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.5=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.10=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2025.3.0=h0e700b2_462
  - mkl-devel=2025.3.0=ha770c72_462
  - mkl-include=2025.3.0=hf2ce2f3_462
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_607
  - openexr=3.4.3=he10986b_0
  - openfst=1.8.4=h84d6215_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.25.0=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - optree=0.17.0=py310h03d9f68_1
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h80abafc_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - protobuf=6.31.1=py310ha36e12e_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - py-opencv=4.12.0=qt6_py310h89973df_607
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.8=h4a9ceb5_0_cpython
  - python-gil=3.10.19=hd8ed1ab_2
  - python_abi=3.10=8_cp310
  - pytorch=2.8.0=cpu_mkl_py310_hf99aa82_102
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py310h3406613_0
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - regex=2025.11.3=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_0
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.22.1=py310h04b4747_0
  - torchaudio=2.8.0=cpu_py310haaebfcf_2
  - torchcodec=0.8.1=cpu_py310_h152ea3e_2
  - torchvision=0.24.0=cpu_py310_h64b0661_2
  - torchvision-extra-decoders=0.0.2=py310h6e8cda3_4
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.17.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.7=hb8e6e7a_2
prefix: /data/upftfg27/lfranceschi/.conda/envs/acl_ssl
