model: ACL

common:
  train_data: vggsound
  epoch: 3
  batch_size: 8
  input_resolution: 352
  ground_truth_resolution: 224
  num_workers: 4
  seed: 0
  loss:
    - acl_i
    - acl_f
    - area_reg
    - silence_l
    - noise_l
    - diff_san_l
  loss_w:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  san: True
  san_real: True
  san_added_noise_tr: True
  san_added_noise_schedule_k: 5

optimizer: Adam
scheduler: null
amp: True

optim_conf:
  Adam:
    module_path: torch.optim
    module_name: Adam
    lr: 0.0001
    weight_decay: 0.0001

  AdamW:
    module_path: torch.optim
    module_name: AdamW
    lr: 0.001

  SGDR:
    module_path: torch.optim
    module_name: SGD
    lr: 0.5
    weight_decay: 0.00001

sched_conf:
  Cosine:
    module_path: torch.optim.lr_scheduler
    module_name: CosineAnnealingLR
    eta_ratio: 0.0